@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Search Employee number"

    usecase UCa as "Details are viewed,
    promotion request supported"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml